### ISSUE TITLE
Missing Uncomment SSL related directives after run Certbot

### ISSUE THREAD

**Issue by Eskies** [digitalocean/nginxconfig.io#130]
Hello, today I visited nginxconfig.io, which seems moved to digitalocean domain. I think it missing step to uncomment SSL related directives after obtaining certbot. 

It's on certbot tab.

Thank you

**Comment by 0xb4lint** [comment]
Thank you!
Fixed in https://github.com/digitalocean/nginxconfig.io/commit/e402ed8b64211f287b88fe8f13962a62b629b7b2.

**Comment by cliffkujala** [comment]
This is still not working with multiple sites.  The space is left out between the paths to the per website config files.  

Step 4 in the Certbot commands with multiple sites produces 
`sed -i -r 's/#?;#//g' /etc/nginx/sites-available/example.com.conf/etc/nginx/sites-available/example.com.conf `

But it should be
`sed -i -r 's/#?;#//g' /etc/nginx/sites-available/example.com.conf /etc/nginx/sites-available/example.com.conf `
